# Generated by Django 3.0.5 on 2020-04-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200420_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='lang',
        ),
    ]
